language: node_js
node_js:
  - '7'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - yarn global add eslint
  - yarn global add stylelint
  - tarn global add mocha
  - yarn run lint
  - yarn run test
